# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Real World Haskell (PT-BR)
email: sergio.costa@ecp.ufma.br
description: >- # this means to ignore newlines until "baseurl:"
 Uma tradução não oficial do livro Real World Haskell de Bryan O’Sullivan, Don Stewart, and John Goerzen

baseurl: "/rwh-ptbr" # the subpath of your site, e.g. /blog
url: "https://Lambda-MA.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: profsergiocosta
github_username:  profsergiocosta

# make search bar appear in top nav?
search_in_topnav: true

# make search bar appear in sidebar?
search_in_sidebar: false

# in responsive view, show sidebar toggle button?
toggle-sidebar-button: true

# in responsive view, show navbar toggle button?
navbar-toggle: true

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  
sidebars:
  - generic
  - jekyllhowto

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
